### ISSUE TITLE
Configuration in Rust

### ISSUE THREAD

**Issue by Brettm12345** [AdaShoelace/hadlock#43]
It would be cool if you could configure the window manager using Rust similar to XMonad

**Comment by AdaShoelace** [comment]
Aside from it being "cool" what benefits do you see with using rust for configuration?

One of the goals of Hadlock was that it should be able to update if the config was changes during runtime without requiring a restart. Using rust for the config would obliterate this completely since the user would have to recompile.

But if you have and example to show I am more than willing to look into it and reconsider if the case is strong enough.

**Comment by Brettm12345** [comment]
Take my [xmonad configuration](../../../brettm12345/xmonad-config) for some examples

**Comment by AdaShoelace** [comment]
I have looked into it and come to the conclusion that config in Rust will not happen.
I want the configuration to be data only and also easy to understand.

For now we are going with regular json but depending on serde's support for rson there might be a change in the future.
